### ISSUE TITLE
Out of Sync with nist metaschema repo

### ISSUE THREAD

**Issue by wandmagic** [metaschema-framework/metaschema#52]
# User Story:

I believe we need a strategy to syncronize this repo with https://github.com/usnistgov/metaschema

namely the SARIF module isn't there.

furthermore, I believe https://github.com/usnistgov/metaschema-xslt has no support for sarif, so either metaschema-xslt would have to catch up to metaschema java and start producing sarif output, or metaschema java should replace metaschema xslt as the reference implementation.

## Goals:

I'd like a strategy that supports the integrity and long term success of metaschema and oscal

## Dependencies:

why isn't this repo considered a fork of the metaschema repo? this makes providing upstream updates more challenging.

## Acceptance Criteria

- [ ] this repo is converted to be a fork of the usnist metaschema
- [ ] a strategy for reference implementation
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire** [comment]
The [usnistgov/metaschema]() repo has not seen any improvements made since [March 15, 2024](https://github.com/usnistgov/metaschema/commit/cf5966076cce4756081a05db46a784f5fb25af27). There have only been small changes to address broken links.

The following PRs have been open in usnistgov/metaschema for a long time, without any movement.
- usnistgov/metaschema#519
- usnistgov/metaschema#552
- usnistgov/metaschema#554
- usnistgov/metaschema#569
- usnistgov/metaschema#659
- usnistgov/metaschema#686
- usnistgov/metaschema#698

There are also 10 dependabot PRs that are open and unresolved. By all indications, there is not much maintenance going on in the usnistgov/metaschema repository.

This repository was stood up to be a place where the specification, schemas, unit tests, and examples can be actively maintained. The PRs mentioned earlier have been merged here. At the moment this repo is 19 commits ahead of the usnistgov repo. As a direct contribution fork, doing this is not really practical. This repo and related website can also be used to post related specification changes, which would not be possible otherwise without PRs getting merged in usnistgov/metaschema.

If at some point, usnistgov/metaschema becomes active again, they can pull changes from this repository if there is interest.

**Comment by wandmagic** [comment]
thanks for that clarification, closing this for now, as given this information, our only course of action is to continue development here.
